package edu.quinnipiac.edu.ser210.tasksappch14

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

//table name
@Entity(tableName = "tak_table")
data class Task {
    //autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    var taskId : Long = 0L,

    //column name
    @ColumnInfo(name = "task_name")
    var taskName: String = "",

    @ColumnInfo(name = "task_done")
    var taskDone: Boolean = false

}